name: GameServer-Start

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 6 * * *'

jobs:
  run_start:
    runs-on: ubuntu-latest
    env:
      WORK_DIR: gameserver
    permissions:
      contents: write

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: yeye296/Auto-Renew-Scripts
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: scripts
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 安装 Python 依赖
        working-directory: scripts/${{ env.WORK_DIR }}
        run: |
          pip install -r requirements.txt -q

      - name: 🚀 运行脚本
        timeout-minutes: 15
        working-directory: scripts/${{ env.WORK_DIR }}
        env:
          PYTHONIOENCODING: utf-8
          USERNAME: ${{ secrets.GAMESERVER_MAIL }}
          PASSWORD: ${{ secrets.GAMESERVER_PASS }}
          PANEL_URL: ${{ secrets.GAMESERVER_PANEL_URL }}
          CHROME_PROXY: "" 
        run: |
          python -u app.py

      - name: Commit and Push Cookie Update
        if: always()
        # 保持在仓库根目录操作 git
        working-directory: scripts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          COOKIE_JSON="${WORK_DIR}/cookies.json"
          if [[ -n $(git status -s "$COOKIE_JSON" 2>/dev/null) ]]; then
            echo "检测到 $COOKIE_JSON 更新"
            git add "$COOKIE_JSON"
            echo "正在提交 Cookie..."
            git commit -m "Auto-update auth cookie in ${WORK_DIR} [skip ci]"
            git push
          else
            echo "Cookie 无变化，跳过提交。"
          fi

      - name: 上传截图产物
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          # 👇 使用变量拼接路径
          path: scripts/${{ env.WORK_DIR }}/screenshots/
          if-no-files-found: ignore
          retention-days: 7
